version: '3.2'

services:
  api:
    container_name: 'Ludotheque_API'
    image: node
    restart: 'no'
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ../../:/home/node/app
    expose:
      - "3000"
    command: "npm run dev"